export const CHART = '<i class="fas fa-chart-bar"></i>';
export const MANAGEMENT = '<i class="fas fa-user-friends"></i>';
export const USER= '<i class="fas fa-user"></i>';
export const TRAINING= '<i class="fas fa-chalkboard-teacher"></i>';
export const ASSESSMENT= '<i class="fas fa-clipboard-list"></i>';
export const DASHBOARD= '<i class="fas fa-chart-line"></i>';
export const ANGLE_DOWN= '<i class="fas fa-angle-down"></i>';
export const CHECK= '<i class="far fa-check-square"></i>';
export const COURSE= '<i class="fas fa-book"></i>';
export const MENU_BARS= '<i class="fas fa-bars"></i>';